# Generated by Django 6.0.4 on 2026-04-17 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('courses_offered', models.CharField(max_length=100)),
                ('grades', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('total_enrolled', models.IntegerField()),
                ('total_waitlist', models.IntegerField()),
                ('demand_level', models.CharField(max_length=50)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('prerequisite_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=50)),
                ('required_gr', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DemandReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_id', models.CharField(max_length=20)),
                ('report_type', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('total_waitlist', models.IntegerField()),
                ('demand_data', models.TextField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grades_app.grade')),
            ],
        ),
    ]
