# Generated by Django 6.0.4 on 2026-04-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Student', models.CharField(max_length=50)),
                ('Payment_Date', models.DateField()),
                ('Payment_Status', models.CharField(max_length=50)),
                ('Payment_Option', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('fullName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=50)),
                ('Phone_No', models.CharField(max_length=12)),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('AccountStatus', models.CharField(max_length=50)),
                ('Admin', models.CharField(max_length=50)),
                ('Permission_Level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('Waitlist_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Request_Date', models.DateField()),
                ('Position_Number', models.IntegerField()),
            ],
        ),
    ]
