# Generated by Django 6.0.4 on 2026-04-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('Program_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Program_Name', models.CharField(max_length=200)),
                ('Program_Code', models.CharField(max_length=20, unique=True)),
                ('Department_ID', models.IntegerField()),
                ('Total_Units', models.IntegerField()),
                ('Program_Duration', models.IntegerField(help_text='Duration in years')),
                ('Associated_Courses', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('Semester_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Academic_Year', models.CharField(help_text='e.g. 2024-2025', max_length=20)),
                ('Term', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('Summer', 'Summer')], max_length=10)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Enrollment_Start', models.DateField()),
                ('Enrollment_End', models.DateField()),
            ],
            options={
                'db_table': 'semester',
            },
        ),
    ]
